### ISSUE TITLE
linux: influxdb 优化

### ISSUE THREAD

**Issue by xwisen** [xwisen/ltw#70]
* 优化项:
. /meta/data/wal 分盘录入，减小磁盘读写压力(主要应该是写)
. 增加tsm内存大小
. 查询语句加上tag过滤
. 不要使用https
. 能批量操作尽量批量操作
. 使用持续查询语句归档老数据
. 使用数据删除策略保留一定时长数据
```toml
[meta]
  dir = "/data/influxdb/meta" #数据分盘有利于读写
  logging-enabled = true
  pprof-enabled = true
[data]
  enabled = true
  dir = "/data/influxdb/data"
  wal-dir = "/data/influxdb/wal"
  wal-logging-enabled = true
  max-series-per-database = 0
  max-values-per-tag = 0
  trace-logging-enabled = true
  query-log-enabled = true
  cache-max-memory-size #默认524288000(500m),修改为5g......对查询好像没什么效果
  cache-snapshot-memory-size #默认26214400(25m),修改为250m......对查询好像没什么效果
[coordinator]
  write-timeout = "10s"
  max-concurrent-queries = 0
  query-timeout = "0"
  log-queries-after = "0"
  max-select-point = 0
  max-select-series = 0
  max-select-buckets = 0
[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true #启用后可以看到请求源地址
[continuous_queries]
  log-enabled = true
  enabled = true
```
